### ISSUE TITLE
Inline-Block Tabs not displaying correctly - 5.0

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#42]
After the 5.0 Update tabs with option:block are falling under each other instead of in a 2 column format.

max-width for xpress-window-rolequarter is set to 50% and they also have margins which causes an overflow. 

```
.xpress-window-rolequarter
{
	width: 100%;
    max-width: 50%;
}
```

Temp fix - max-width reduced to 49%

![microsoftteams-image](https://user-images.githubusercontent.com/25164973/32088425-eaeda1ee-bb2e-11e7-938d-4977862e030d.png)

Note: Other display issue is icons aren't mapped - unrelated to this issue

**Comment by JasonBev** [comment]
Additional: `.xpress-window-block` has the same issue.

**Comment by paulfisher53** [comment]
I've changed the flat skin so that the max-width for both `xpress-window-rolequarter` and `xpress-window-block` is `max-width: calc(50% - 10px);` 

This should now take into account the margin. Let me know hoe it goes

**Comment by JasonBev** [comment]
`xpress-window-rolequarter` - Displays nicely
`xpress-window-block` - Does have a minor alignment issue when a tab with 'factbox' is present on the page. I have looked at sites prior to liveapp 5.0 and they have the same issue though, it's just only become noticeable as I modified headers for `.app-window-title-alt`.
Changing it to -5px still doesn't align perfectly for some reason but isn't a major issue.

Mod colour and -10px
![capture2](https://user-images.githubusercontent.com/25164973/32262405-8ccb6986-bf28-11e7-8c0c-c81ac419a0d2.PNG)

Default colour and -5px
![capture3](https://user-images.githubusercontent.com/25164973/32262406-8ef317a4-bf28-11e7-8b66-9c79b03105ae.PNG)

**Comment by paulfisher53** [comment]
The issue is that we are subtracting the wrong amount (we should only subtract the margin, which is 5px) and the `.xpress-window-default` (and other full width classes) also need to subtract the margin. 

Try replacing the following classes:

```css
.xpress-window-right
{
    width: 100%;
    max-width: calc(100% - 5px);		
}

.xpress-window-block
{
    width: 100%;
    max-width: calc(50% - 5px);
}

.xpress-window-rolehalf
{
    width: 100%;
    max-width: calc(100% - 5px); 
}

.xpress-window-rolequarter
{
    width: 100%;
    max-width: calc(50% - 5px);
}

.xpress-window-default
{
    width: 100%;
    max-width: calc(100% - 5px);   
}
```
